### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Findus23** [OctoPrint/OctoPrint-Pushbullet#1]
I tried to install this plugin with the newest version of octoprint on octopi. (https://github.com/foosel/OctoPrint/commit/06fb249f2e1e78651d84da8080946e64351a134b)

The following error occurs:
```bash
pi@octopi ~/OctoPrint $ ~/oprint/bin/pip install https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
```
```
Downloading/unpacking https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
  Downloading master.zip
  Running setup.py egg_info for package from https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-Pqvac6-build/setup.py", line 16, in <module>
        "pushbullet.py"
      File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_931_g06fb249-py2.7.egg/octoprint_setuptools/__init__.py", line 494, in create_plugin_setup_parameters
        packages = find_packages(where=source_folder, exclude=ignored_packages, include=[package, "{package}.*".format(**locals())] + additional_packages)
    TypeError: find_packages() got an unexpected keyword argument 'include'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-Pqvac6-build/setup.py", line 16, in <module>

    "pushbullet.py"

  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_931_g06fb249-py2.7.egg/octoprint_setuptools/__init__.py", line 494, in create_plugin_setup_parameters

    packages = find_packages(where=source_folder, exclude=ignored_packages, include=[package, "{package}.*".format(**locals())] + additional_packages)

TypeError: find_packages() got an unexpected keyword argument 'include'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-Pqvac6-build
Storing complete log in /home/pi/.pip/pip.log
```
If it helps you, here is the content of `/home/pi/.pip/pip.log`:
```
------------------------------------------------------------
/home/pi/oprint/bin/pip run on Wed Jun 10 16:00:31 2015
Downloading/unpacking https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip

  Downloading master.zip

  Downloading from URL https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
  Running setup.py egg_info for package from https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/tmp/pip-Pqvac6-build/setup.py", line 16, in <module>

        "pushbullet.py"

      File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_931_g06fb249-py2.7.egg/octoprint_setuptools/__init__.py", line 494, in create_plugin_setup_parameters

        packages = find_packages(where=source_folder, exclude=ignored_packages, include=[package, "{package}.*".format(**locals())] + additional_packages)

    TypeError: find_packages() got an unexpected keyword argument 'include'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-Pqvac6-build/setup.py", line 16, in <module>

    "pushbullet.py"

  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_931_g06fb249-py2.7.egg/octoprint_setuptools/__init__.py", line 494, in create_plugin_setup_parameters

    packages = find_packages(where=source_folder, exclude=ignored_packages, include=[package, "{package}.*".format(**locals())] + additional_packages)

TypeError: find_packages() got an unexpected keyword argument 'include'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /tmp/pip-Pqvac6-build

Exception information:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-Pqvac6-build
```
Am I doing something wrong or is there a bug in the plugin (or octoprint)?

**Comment by Findus23** [comment]
Update: Other plugins are also not working, so it is a problem with octoprint.
-> https://github.com/foosel/OctoPrint/issues/931

**Comment by foosel** [comment]
Reopening after your [second log](https://github.com/foosel/OctoPrint/issues/931#issuecomment-110780172) in foosel/OctoPrint#931:

```
pi@octopi ~ $ ~/oprint/bin/pip install https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Downloading/unpacking https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
  Downloading master.zip
  Running setup.py egg_info for package from https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip

Requirement already satisfied (use --upgrade to upgrade): OctoPrint in ./oprint/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_931_g06fb249-py2.7.egg (from OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests in ./oprint/lib/python2.7/site-packages (from OctoPrint-Pushbullet==0.1.0)
Downloading/unpacking pushbullet.py (from OctoPrint-Pushbullet==0.1.0)
  Running setup.py egg_info for package pushbullet.py
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/oprint/build/pushbullet.py/setup.py", line 15, in <module>
        install_reqs = parse_requirements("requirements.txt",  session=uuid.uuid1())
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/oprint/build/pushbullet.py/setup.py", line 15, in <module>

    install_reqs = parse_requirements("requirements.txt",  session=uuid.uuid1())

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/oprint/build/pushbullet.py
Storing complete log in /home/pi/.pip/pip.log
```

**Comment by Findus23** [comment]
>You had to force although you did provide the ==7.0 part as well? Shouldn't be the case...

```
pi@octopi ~ $ ~/oprint/bin/pip install setuptools==7.0
Requirement already satisfied (use --upgrade to upgrade): distribute in ./oprint/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg
Cleaning up...
```

**Comment by foosel** [comment]
I hate those little differences in behaviours between the various versions of pip that are out there...

For comparison:
```
pi@octopi ~/oprint $ ~/oprint/bin/pip install setuptools==7.0
You are using pip version 6.1.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting setuptools==7.0
/home/pi/oprint/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading setuptools-7.0-py2.py3-none-any.whl (534kB)
    100% |████████████████████████████████| 536kB 25kB/s
Installing collected packages: setuptools
  Found existing installation: distribute 0.6.24
    Uninstalling distribute-0.6.24:
      Successfully uninstalled distribute-0.6.24
Successfully installed setuptools-7.0
```

**Comment by Findus23** [comment]
That looks completly different even than my successful install:
```
pi@octopi ~ $ ~/oprint/bin/pip install --upgrade setuptools==7.0
Downloading/unpacking distribute from https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6c59594a7b180af57af8a0cc0cf5b4a
  Downloading distribute-0.7.3.zip (145Kb): 145Kb downloaded
  Running setup.py egg_info for package distribute
    
Downloading/unpacking setuptools>=0.7 (from distribute)
  Downloading setuptools-17.1.1.tar.gz (630Kb): 630Kb downloaded
  Running setup.py egg_info for package setuptools
    
Installing collected packages: distribute, setuptools
  Found existing installation: distribute 0.6.24
    Uninstalling distribute:
      Successfully uninstalled distribute
  Running setup.py install for distribute
    
  Found existing installation: distribute 0.6.24
    Uninstalling distribute:
      Successfully uninstalled distribute
  Running setup.py install for setuptools
    
    Installing easy_install script to /home/pi/oprint/bin
    Installing easy_install-2.7 script to /home/pi/oprint/bin
Successfully installed distribute setuptools
Cleaning up...
```
```
pi@octopi ~ $ ~/oprint/bin/pip --version
pip 1.1 from /home/pi/oprint/lib/python2.7/site-packages/pip-1.1-py2.7.egg (python 2.7)
 ```
I have installed octopi about half a year ago.

**Comment by foosel** [comment]
As I said, different versions with different behaviour. Looking into it. It's like herding cats though.

**Comment by foosel** [comment]
Ok, that took a while to reproduce (had to downgrade my pip version and clear a couple of caches first), but now I at least see the same issue as you. As suspected from the log the `pushbullet` dependency is at fault here, not the plugin itself. I'll try to find a workaround (I can't just patch `pushbullet` obviously). 

An easy fix would probably be to just update pip.

**Comment by foosel** [comment]
See also randomchars/pushbullet.py#36

**Comment by Findus23** [comment]
That did it. Now everything is working:
```
pi@octopi ~ $ ~/oprint/bin/pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/source/p/pip/pip-7.0.3.tar.gz#md5=54cbf5ae000fb3af3367345f5d299d1c
  Downloading pip-7.0.3.tar.gz (1.1Mb): 1.1Mb downloaded
  Running setup.py egg_info for package pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Installing collected packages: pip
  Found existing installation: pip 1.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
    Installing pip script to /home/pi/oprint/bin
    Installing pip2.7 script to /home/pi/oprint/bin
    Installing pip2 script to /home/pi/oprint/bin
Successfully installed pip
Cleaning up...
```
```
pi@octopi ~ $ ~/oprint/bin/pip install https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): OctoPrint in ./oprint/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_931_g06fb249-py2.7.egg (from OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests in ./oprint/lib/python2.7/site-packages (from OctoPrint-Pushbullet==0.1.0)
Collecting pushbullet.py (from OctoPrint-Pushbullet==0.1.0)
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pushbullet.py-0.8.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): flask<0.11,>=0.9 in /usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.8.3 in /usr/local/lib/python2.7/dist-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): tornado==4.0.1 in /usr/local/lib/python2.7/dist-packages/tornado-4.0.1-py2.7-linux-armv6l.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): sockjs-tornado>=1.0.0 in /usr/local/lib/python2.7/dist-packages/sockjs_tornado-1.0.1-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /usr/local/lib/python2.7/dist-packages/PyYAML-3.10-py2.7-linux-armv6l.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.2.2 in /usr/local/lib/python2.7/dist-packages/Flask_Login-0.2.2-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Principal==0.3.5 in /usr/local/lib/python2.7/dist-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Babel==0.9 in /usr/local/lib/python2.7/dist-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Assets==0.10 in ./oprint/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pyserial in ./oprint/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/local/lib/python2.7/dist-packages/netaddr-0.7.12-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): watchdog in /usr/local/lib/python2.7/dist-packages/watchdog-0.8.2-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): sarge>=0.1.4 in ./oprint/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): netifaces in /usr/local/lib/python2.7/dist-packages/netifaces-0.10.4-py2.7-linux-armv6l.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pylru in /usr/local/lib/python2.7/dist-packages/pylru-1.0.6-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): rsa in /usr/local/lib/python2.7/dist-packages/rsa-3.1.4-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pkginfo in ./oprint/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): semantic-version in ./oprint/lib/python2.7/site-packages/semantic_version-2.3.1-py2.7.egg (from OctoPrint->OctoPrint-Pushbullet==0.1.0)
Collecting python-magic (from pushbullet.py->OctoPrint-Pushbullet==0.1.0)
  Downloading python-magic-0.4.6.tar.gz
Collecting websocket-client (from pushbullet.py->OctoPrint-Pushbullet==0.1.0)
  Downloading websocket_client-0.32.0.tar.gz (192kB)
    100% |████████████████████████████████| 192kB 71kB/s 
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages/Jinja2-2.7.3-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages/certifi-14.05.14-py2.7.egg (from tornado==4.0.1->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages/backports.ssl_match_hostname-3.4.0.2-py2.7.egg (from tornado==4.0.1->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): blinker in /usr/local/lib/python2.7/dist-packages/blinker-1.3-py2.7.egg (from Flask-Principal==0.3.5->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in ./oprint/lib/python2.7/site-packages/Babel-1.3-py2.7.egg (from Flask-Babel==0.9->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /usr/local/lib/python2.7/dist-packages/speaklater-1.3-py2.7.egg (from Flask-Babel==0.9->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): webassets>=0.10 in ./oprint/lib/python2.7/site-packages/webassets-0.10.1-py2.7.egg (from Flask-Assets==0.10->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /usr/local/lib/python2.7/dist-packages/argh-0.26.1-py2.7.egg (from watchdog->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /usr/local/lib/python2.7/dist-packages/pathtools-0.1.2-py2.7.egg (from watchdog->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /usr/local/lib/python2.7/dist-packages/pyasn1-0.1.7-py2.7.egg (from rsa->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six in ./oprint/lib/python2.7/site-packages/six-1.8.0-py2.7.egg (from websocket-client->pushbullet.py->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/dist-packages/MarkupSafe-0.23-py2.7-linux-armv6l.egg (from Jinja2>=2.4->flask<0.11,>=0.9->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /usr/local/lib/python2.7/dist-packages (from Babel>=1.0->Flask-Babel==0.9->OctoPrint->OctoPrint-Pushbullet==0.1.0)
Installing collected packages: python-magic, websocket-client, pushbullet.py, OctoPrint-Pushbullet
  Running setup.py install for python-magic
  Running setup.py install for websocket-client
  Running setup.py install for OctoPrint-Pushbullet
Successfully installed OctoPrint-Pushbullet-0.1.0 pushbullet.py-0.8.1 python-magic-0.4.6 websocket-client-0.32.0
```

**Comment by foosel** [comment]
I also pushed a new version which uses a patched version of the dependency (which I created a PR for) and adjusted the plugin manager in OctoPrint to allow for successful installation of this.

**Comment by Findus23** [comment]
Something very odd happened:
I have reinstalled octopi because of a problem with my webcam (which got solved this way).
I updated pip the same way as I did before, but now the issue still exists.
```
pi@octopi ~ $ ~/oprint/bin/pip install setuptools==7.0
Requirement already satisfied (use --upgrade to upgrade): setuptools==7.0 in ./oprint/lib/python2.7/site-packages
```
```
pi@octopi ~ $ ~/oprint/bin/pip install --upgrade pip
Requirement already up-to-date: pip in ./oprint/lib/python2.7/site-packages
```
```
pi@octopi ~ $ ~/oprint/bin/pip install https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Collecting https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-mQZNRv-build/setup.py", line 16, in <module>
        "pushbullet.py==dev"
      File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_934_g6a7a858-py2.7.egg/octoprint_setuptools/__init__.py", line 494, in create_plugin_setup_parameters
        packages = find_packages(where=source_folder, exclude=ignored_packages, include=[package, "{package}.*".format(**locals())] + additional_packages)
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-mQZNRv-build
pi@octopi ~ $ 
```
Am I missing something?

**Comment by Findus23** [comment]
Update:
It seems to be a problem with octoprint as I am also not able to install https://github.com/Salandora/OctoPrint-SystemCommandEditor/commit/a910402696247029dcef5984f19b774101af0985 
```
pi@octopi ~/OctoPrint $ ~/oprint/bin/pip install https://github.com/Salandora/OctoPrint-SystemCommandEditor/archive/master.zip

Collecting https://github.com/Salandora/OctoPrint-SystemCommandEditor/archive/master.zip
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/Salandora/OctoPrint-SystemCommandEditor/archive/master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-_paQYK-build/setup.py", line 64, in <module>
        additional_data=plugin_additional_data
      File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_934_g6a7a858-py2.7.egg/octoprint_setuptools/__init__.py", line 494, in create_plugin_setup_parameters
        packages = find_packages(where=source_folder, exclude=ignored_packages, include=[package, "{package}.*".format(**locals())] + additional_packages)
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_paQYK-build
```
Many other plugins like https://github.com/Booli/OctoPrint-ActionTriggerPlugin/commit/ecc77de7b22fd033892ee8ac6acc06f9a1ad75b1 are working.
```
pi@octopi ~/OctoPrint $ ~/oprint/bin/pip install https://github.com/Booli/OctoPrint-ActionTriggerPlugin/archive/master.zip
Collecting https://github.com/Booli/OctoPrint-ActionTriggerPlugin/archive/master.zip
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/Booli/OctoPrint-ActionTriggerPlugin/archive/master.zip
     / 32kB 222kB/s
  Requirement already satisfied (use --upgrade to upgrade): OctoPrint-ActionTriggerPlugin==0.1 from https://github.com/Booli/OctoPrint-ActionTriggerPlugin/archive/master.zip in /home/pi/oprint/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): OctoPrint in /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_934_g6a7a858-py2.7.egg (from OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): setuptools==7.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): flask<0.11,>=0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask-0.9-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): tornado==4.0.1 in /home/pi/oprint/lib/python2.7/site-packages/tornado-4.0.1-py2.7-linux-armv6l.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): sockjs-tornado>=1.0.0 in /home/pi/oprint/lib/python2.7/site-packages/sockjs_tornado-1.0.1-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /home/pi/oprint/lib/python2.7/site-packages/PyYAML-3.10-py2.7-linux-armv6l.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.2.2 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Login-0.2.2-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Principal==0.3.5 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Babel==0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): Flask-Assets==0.10 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): pyserial in /home/pi/oprint/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): netaddr in /home/pi/oprint/lib/python2.7/site-packages/netaddr-0.7.13-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): watchdog in /home/pi/oprint/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): sarge>=0.1.4 in /home/pi/oprint/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): netifaces in /home/pi/oprint/lib/python2.7/site-packages/netifaces-0.10.4-py2.7-linux-armv6l.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): pylru in /home/pi/oprint/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): rsa in /home/pi/oprint/lib/python2.7/site-packages/rsa-3.1.4-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): pkginfo in /home/pi/oprint/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): semantic-version in /home/pi/oprint/lib/python2.7/site-packages/semantic_version-2.4.1-py2.7.egg (from OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/pi/oprint/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/pi/oprint/lib/python2.7/site-packages/certifi-2015.04.28-py2.7.egg (from tornado==4.0.1->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/pi/oprint/lib/python2.7/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.7.egg (from tornado==4.0.1->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): blinker in /home/pi/oprint/lib/python2.7/site-packages/blinker-1.3-py2.7.egg (from Flask-Principal==0.3.5->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in /home/pi/oprint/lib/python2.7/site-packages/Babel-1.3-py2.7.egg (from Flask-Babel==0.9->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /home/pi/oprint/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg (from Flask-Babel==0.9->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): webassets>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/webassets-0.10.1-py2.7.egg (from Flask-Assets==0.10->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /home/pi/oprint/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg (from watchdog->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg (from watchdog->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages/pyasn1-0.1.7-py2.7.egg (from rsa->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/pi/oprint/lib/python2.7/site-packages/MarkupSafe-0.23-py2.7-linux-armv6l.egg (from Jinja2>=2.4->flask<0.11,>=0.9->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /home/pi/oprint/lib/python2.7/site-packages/pytz-2014.10-py2.7.egg (from Babel>=1.0->Flask-Babel==0.9->OctoPrint->OctoPrint-ActionTriggerPlugin==0.1)
```
It is really odd that it worked yesterday.

**Comment by foosel** [comment]
It's what I feared could happen (I've seen it happen in the past that one second the library version from the virtualenv is taken, the next the one from the system site package), which is why I pushed a change to OctoPrint yesterday that changes things so that no new setuptools are needed, and also changed the pushbullet plugin to use a patched version of pushbullet.py.

If you update OctoPrint to the current version of master it should work.

**Comment by Findus23** [comment]
I have seen that you also added the changes to devel, so I updated and now https://github.com/Salandora/OctoPrint-SystemCommandEditor/commit/a910402696247029dcef5984f19b774101af0985 is working.
But now I have another issue (this time relatet to pushbullet):
```
pi@octopi ~/OctoPrint $ ~/oprint/bin/pip install https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Collecting https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): OctoPrint in /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.0_dev_937_gc527338-py2.7.egg (from OctoPrint-Pushbullet==0.1.1)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Pushbullet==0.1.1)
Collecting pushbullet.py==dev (from OctoPrint-Pushbullet==0.1.1)
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement pushbullet.py==dev (from OctoPrint-Pushbullet==0.1.1) (from versions: 0.4.1, 0.5.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1)
No matching distribution found for pushbullet.py==dev (from OctoPrint-Pushbullet==0.1.1)
```

**Comment by foosel** [comment]
Did you install it manually or from the plugin repository?

**Comment by foosel** [comment]
Never mind, obviously manually. Add "--process-dependency-links" to the command line for that one please. If you install it via Plugin Manager, that will take care of that for you, but from the command line (why are you using that btw?) you need to add it yourself:

    ~/oprint/bin/pip install --process-dependency-links https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip

Reason being the patched version of pushbullet.py that I need to pull in from my own repo since my PR hasn't been merged yet in the project's repo.

**Comment by Findus23** [comment]
>(why are you using that btw?)

Because the error messages when a plugin installation failed are not that helpful.
But now the installation works with the Plugin Manager and with pip.

Thank you for the help with my (not so few) problems.

I just have one more question: Why are you using the dev branch of https://github.com/foosel/pushbullet.py/tree/dev if it is even with the original reposity?
![bildschirmfoto vom 2015-06-12 09-22-48](https://cloud.githubusercontent.com/assets/6266037/8125264/a0491aa2-10e4-11e5-90fd-2ab4c87747af.png)

**Comment by foosel** [comment]
> Because the error messages when a plugin installation failed are not that helpful.
It's logging exactly what pip outputs in the little dialog.

> I just have one more question: Why are you using the dev branch
I'm not. I'm declaring what's on the master branch as the `dev` **version** of the package to install:

    dependency_links=[
        https://github.com/foosel/pushbullet.py/archive/master.zip#egg=pushbullet.py-dev
    ]

This tells pip that if I want it to install the pushbullet.py package in version `dev` that it can find it at the above address. This part of `setup.py` only gets evaluated by pip if you supply `--process-dependency-links` with the call to pip, which is why you ran into the "No matching distribution found for pushbullet.py==dev" problem earlier.

Sorry for the problems, but I did not expect that the dependency of the plugin would cause these kinds problems with older versions of pip. At least there now exists an additional workaround for plugins that need external dependencies like that patched version in OctoPrint as a consequence of these problems. Not pretty, but works. And your failed manual attempt also made me adjust the installation instructions on plugins.octoprint.org ;)

![image](https://cloud.githubusercontent.com/assets/83657/8125548/c39390bc-10e6-11e5-928a-c0a540515b87.png)

![image](https://cloud.githubusercontent.com/assets/83657/8125554/d16a9564-10e6-11e5-9f09-4ad4969ddc9a.png)

**Comment by pauly7300** [comment]
Thanks to you both for allowing me to come along ~5 hours after you were done with this thread and live the exact same experience only to make my way out based on your comments/instructions.  :)
